### ISSUE TITLE
Build successfully, but fail to test.

### ISSUE THREAD

**Issue by Queequeg92** [jyh2986/Active-Shift-TF#1]
Hi, I have followed your instructions to build the Op successfully. Then I tried to run the test code. And I got the error message:
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'ActiveShift2DOp' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]

Could you help to figure out what is wrong? Thank you!

**Comment by jyh2986** [comment]
This implementation only supports GPU operation. As you tested in CPU mode, you got an error message. Please run in GPU mode.

**Comment by Queequeg92** [comment]
@jyh2986 
Thanks for your reply! Finally, I find that it was caused by the default configuration of GPU device. The default GPU is set to GPU 2 in your test code. It will get the error when running on a machine with less than 3 GPUs. I have pulled requests to fix it.
